version: "3.3"

services:
  opentracker:
    image: opentracker
    networks:
      btnet:
        ipv4_address: 10.5.0.5
  node-1:
    image: vertx-bittorrent
    hostname: node-1
    volumes:
      - ./src/main/resources/test-data/:/train
    environment:
      - >-
        EXTRA_OPTS=--images-path /train/t10k-images-idx3-ubyte
        --labels-path /train/t10k-labels-idx1-ubyte
      - NODE_ID=1
      - OTHER_NODES=node-2:54321,node-3:54321
    cap_add:
      - NET_ADMIN
    networks:
      btnet:
        ipv4_address: 10.5.0.2
  node-2:
    image: vertx-bittorrent
    hostname: node-2
    volumes:
      - ./src/main/resources/train/:/train
    environment:
      - >-
        EXTRA_OPTS=--images-path /train/train-images-idx3-ubyte
        --labels-path /train/train-labels-idx1-ubyte
      - NODE_ID=2
      - OTHER_NODES=node-1:54321,node-3:54321
    cap_add:
      - NET_ADMIN
    networks:
      btnet:
        ipv4_address: 10.5.0.3
  node-3:
    image: vertx-bittorrent
    hostname: node-3
    environment:
      - VB_IS_FREE_RIDER=true
      - NODE_ID=3
      - OTHER_NODES=node-1:54321,node-2:54321
    cap_add:
      - NET_ADMIN
    networks:
      btnet:
        ipv4_address: 10.5.0.4

networks:
  btnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
